### ISSUE TITLE
upgrade to Legolas 0.5

### ISSUE THREAD

**Issue by a-cakir** [beacon-biosignals/Lighthouse.jl#96]
We define two schemas
- `"lighthouse.evaluation@1",`
- `"lighthouse.observation@1"`
- `"lighthouse.class@1"`
- `"lighthouse.label-metrics@1" > "lighthouse.class@1"`
- `"lighthouse.hardened-metrics@1" >"lighthouse.class@1"`
- `"lighthouse.tradeoff-metrics@1" >"lighthouse.class@1"`

We use `Legolas.validate` in code and tests.

## TODOs

- [ ] upgrade evaluation schema
- [ ] upgrade observation schema
- [ ] upgrade class schema
- [ ] upgrade label-metrics schema
- [ ] upgrade hardened-metrics schema
- [ ] upgrade tradeoff-metrics schema
